"""Manual small parent -> normal harvest writer -> stopped DB -> fresh retained read."""
from hashlib import sha256
import importlib.util
import json
import os
from pathlib import Path
import subprocess
import sys


def source_inventory(roots):
    result = {}
    for root in roots:
        for path in (root,*sorted(root.rglob('*'))):
            info = path.lstat();assert not path.is_symlink()
            result[str(path)] = (info.st_dev,info.st_ino,info.st_mode,info.st_size,info.st_mtime_ns,info.st_ctime_ns,
                sha256(path.read_bytes()).hexdigest() if path.is_file() else None)
    return result


def test_owned_preserved_parent_normal_harvest_registration_and_fresh_restore():
    root = Path(__file__).resolve().parents[2]
    spec = importlib.util.spec_from_file_location('manual_harvest_storage',root/'research/crop-harvest-storage-preservation.py')
    storage = importlib.util.module_from_spec(spec);spec.loader.exec_module(storage)
    stage = Path(os.environ['OSSF_HARVEST_STORAGE_STAGE'])
    parent = Path(os.environ['OSSF_HARVEST_STORAGE_PARENT']);parent_sha = os.environ['OSSF_HARVEST_STORAGE_PARENT_SHA256']
    original = storage.backup.checked(parent,parent_sha)
    config = json.loads(storage.runtime.private_bytes(parent.parent/'original-runtime.private'))
    source_roots = [Path(config['input']['directory']),Path(config['server_directory'])]
    original_source = source_inventory(source_roots);before_FD = len(os.listdir('/proc/self/fd'))
    # Parent backup and its signed inputs/artifact are never regenerated by this test.
    original_files = {p:(p.stat().st_dev,p.stat().st_ino,p.stat().st_mode,sha256(p.read_bytes()).hexdigest())
        for p in parent.parent.iterdir() if p.is_file()}
    path,digest = storage.register(parent,parent_sha,stage/'registered')
    value = storage.checked(path,digest)
    assert value['source']['result_id'] == original['original_record']['result_id']
    assert value['source']['payload_sha256'] == original['original_record']['payload_sha256']
    assert value['pages']['first']['total'] == value['pages']['first']['count'] == 5
    assert value['pages']['last']['count'] == 1
    assert not (path.parent/'source-parent/data/postmaster.pid').exists()
    child_out = stage/'fresh-read.private.json';log = stage/'fresh-read.private-log'
    argv = [sys.executable,str(root/'research/crop-harvest-storage-preservation.py'),
        '--manifest',str(path),'--sha256',digest,'--restore-directory',str(stage/'fresh-restore'),
        '--output',str(child_out)]
    with log.open('xb') as stream:
        os.fchmod(stream.fileno(),0o600)
        child = subprocess.run(argv,stdout=stream,stderr=subprocess.STDOUT,timeout=300,check=False)
    log.chmod(0o400)
    assert child.returncode == 0
    observed = json.loads(storage.runtime.private_bytes(child_out))
    assert all(observed[k] == value[k] for k in ('original_record','source','summary_sha256','pages'))
    assert observed['current_rights_scope_tenant_denied_and_restored']
    assert observed['guarded_RHS_row_generation_publication_proof_calls'] == 0
    assert observed['restored_postmaster_absent']
    assert all((p.stat().st_dev,p.stat().st_ino,p.stat().st_mode,sha256(p.read_bytes()).hexdigest()) == expected
        for p,expected in original_files.items())
    assert source_inventory(source_roots) == original_source
    assert len(os.listdir('/proc/self/fd')) == before_FD
    storage.backup.write(stage/'accepted.private.json',storage.canonical({'manifest':str(path),'sha256':digest,
        'fresh_actual_exit_code':child.returncode,'original_backup_preserved':True,'current_query':observed,
        'original_input_artifact_identity_and_bytes_preserved':True,'source_entries':len(original_source),
        'FD_before_after':[before_FD,len(os.listdir('/proc/self/fd'))],
        'actual_crop_Runs':0,'G0_G4':'not_assessed'}))
